services:
  iparoom:
    ports: !reset []
    environment:
      IPAROOM_CA_ROOT_URL: http://caddy:8080/root.crt
      IPAROOM_CA_INSTALL_URL: http://${IPAROOM_COMPOSE_HOSTNAME}:${IPAROOM_COMPOSE_CA_PORT}/ca
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - iparoom
    ports:
      - '${IPAROOM_COMPOSE_HOST}:${IPAROOM_COMPOSE_PORT}:443'
      - '${IPAROOM_COMPOSE_HOST}:${IPAROOM_COMPOSE_CA_PORT}:8080'
    environment:
      IPAROOM_HOSTNAME: ${IPAROOM_COMPOSE_HOSTNAME}
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - '${IPAROOM_COMPOSE_ROOT}/caddy/data:/data'
      - '${IPAROOM_COMPOSE_ROOT}/caddy/config:/config'
